#!/bin/zsh
touch /var/log/powersave.log
echo "@`date --iso-8601=seconds`- powersave: $1" >> /var/log/powersave.log

. /etc/powersave.config
PATH="/usr/sbin:/sbin:$PATH"

init $1

cat >> /var/log/powersave.log <<EOF
Bus power control: $BUSPOWERCONTROL
Usb auto suspend: $USBAUTOSUSPEND
NMI watchdog: $NMIWATCHDOG
Cpu governor: $CPUGOVERNOR
PCIE aspm: $PCIE_ASPM
Vm laptop mode: $LAPTOP_MODE
Vm dirty ratio: $VMDIRTY_RATIO
Vm dirty background ratio: $VMDIRTY_BACKGROUND
Vm expire centisecs: $VMDIRTY_EXPIRE
Vm dirty write centisecs: $VMDIRTY_WRITE
hdparms: $HDPARM
link power: $SCSI_LINKPOWER
snd powersave: $SND_POWERSAVE
snd power save controller: $SND_POWERSAVECTRL
wlan: $WLAN_MODE
xset: $XSET_MODE
xset dpms: $DPMS
EOF

# bus
for i in /sys/bus/*/devices/*/power/control; do echo $BUSPOWERCONTROL > $i; done
# usb autosuspend
for i in /sys/bus/usb/devices/*/power/autosuspend; do echo $USBAUTOSUSPEND > $i; done
# nmi_watchdog
echo $NMIWATCHDOG > /proc/sys/kernel/nmi_watchdog
# cpu
exec cpupower frequency-set  -g $CPUGOVERNOR >/dev/null &
# aspm
echo $PCIE_ASPM > /sys/module/pcie_aspm/parameters/policy
# kernel write mode
echo $LAPTOP_MODE> /proc/sys/vm/laptop_mode
echo $VMDIRTY_RATIO > /proc/sys/vm/dirty_ratio
echo $VMDIRTY_BACKGROUND > /proc/sys/vm/dirty_background_ratio
echo $VMDIRTY_EXPIRE > /proc/sys/vm/dirty_expire_centisecs
echo $VMDIRTY_WRITE > /proc/sys/vm/dirty_writeback_centisecs
# disk powersave
for disk in $DISKS; do
  exec hdparm $HDPARM $disk >/dev/null &
done
for i in /sys/class/scsi_host/host*/link_power_management_policy; do echo $SCSI_LINKPOWER > $i; done
# sound card powersave
for i in /sys/module/snd_*/parameters/power_save; do echo $SND_POWERSAVE > $i; done
for i in /sys/module/snd_*/parameters/power_save_controller; do echo $SND_POWERSAVECTRL > $i; done
# wlan0 powersave
exec iw dev $wlan $WLAN_MODE >/dev/null &
# screen powersave
for i in /sys/class/backlight/*; do
  get_brightness $1 $i
  cat >> /var/log/powersave.log <<EOF
$(basename $i)/brightness: $BRIGHTNESS
EOF
  echo $BRIGHTNESS > "$i/brightness"
done
exec xset $XSET_MODE &
exec xset dpms $DPMS &

post $1

exit 0
